configfile: "config/config.yaml"

include: "rules/common.smk"


rule all:
    input:
        expand(f"{ANALYSIS_DIR}/qc/fastp/{{sample}}.fastp.html", sample=SAMPLE_NAMES),
        expand(f"{ANALYSIS_DIR}/qc/fastp/{{sample}}.fastp.json", sample=SAMPLE_NAMES),
        expand(f"{ANALYSIS_DIR}/qc/fastqc/{{sample}}", sample=SAMPLE_NAMES),
        expand(f"{ANALYSIS_DIR}/bam/{{sample}}.markdup.bam", sample=SAMPLE_NAMES),
        expand(f"{ANALYSIS_DIR}/bam/{{sample}}.markdup.bam.bai", sample=SAMPLE_NAMES),
        expand(f"{ANALYSIS_DIR}/qc/samtools/{{sample}}.flagstat.txt", sample=SAMPLE_NAMES),
        expand(f"{ANALYSIS_DIR}/qc/samtools/{{sample}}.stats.txt", sample=SAMPLE_NAMES),
        expand(f"{ANALYSIS_DIR}/qc/picard/{{sample}}.markduplicates.metrics.txt", sample=SAMPLE_NAMES),
        expand(f"{ANALYSIS_DIR}/qc/picard/{{sample}}.insert_size.metrics.txt", sample=SAMPLE_NAMES),
        expand(f"{ANALYSIS_DIR}/qc/picard/{{sample}}.insert_size.pdf", sample=SAMPLE_NAMES),
        expand(f"{ANALYSIS_DIR}/qc/picard/{{sample}}.hs_metrics.txt", sample=SAMPLE_NAMES),
        expand(f"{ANALYSIS_DIR}/qc/picard/{{sample}}.per_target_coverage.txt", sample=SAMPLE_NAMES),
        expand(f"{ANALYSIS_DIR}/qc/depth/{{sample}}.capture_depth.summary.tsv", sample=SAMPLE_NAMES),
        expand(f"{ANALYSIS_DIR}/qc/depth/{{sample}}.loci_depth.summary.tsv", sample=SAMPLE_NAMES),
        expand(f"{ANALYSIS_DIR}/qc/duplicates/{{sample}}.duplicate_fragments.summary.tsv", sample=SAMPLE_NAMES),
        expand(f"{ANALYSIS_DIR}/qc/duplicates/{{sample}}.duplicate_fragments.top.tsv", sample=SAMPLE_NAMES),
        expand(f"{ANALYSIS_DIR}/qc/duplicates/{{sample}}.duplicate_fragments.histogram.tsv", sample=SAMPLE_NAMES),
        expand(f"{ANALYSIS_DIR}/qc/qualimap/{{sample}}", sample=SAMPLE_NAMES),


include: "rules/fastq.smk"
include: "rules/bwa.smk"
include: "rules/samtools.smk"
include: "rules/picard.smk"
include: "rules/coverage.smk"
include: "rules/qc.smk"
